#+TITLE: Conformal Solitons for the Mean Curvature Flow
#+AUTHOR: Paul Bryan and Mu-Tao Wang
#+SETUPFILE: ~/.emacs.d/org-templates/bibliography.org
#+OPTIONS: toc:nil

# ***  Class
#+LATEX_CLASS: amsart

# *** Macros
#+LATEX_HEADER: \input{local_definitions}

# *** For bundling
#+LATEX_HEADER: \usepackage{snapshot}

# *** Author
#+LATEX_HEADER: \address{Department of Mathematics, University of California San Diego}
#+LATEX_HEADER: \email{pbryan@ucsd.edu}
#+LATEX_HEADER: \address{Department of Mathematics, Columbia University}
#+LATEX_HEADER: \email{mtwang@math.columbia.edu}

# *** Metadata
#+LaTeX_HEADER: \keywords{Mean Curvature Flow, Solitons, Conformal Geometry}
#+LATEX_HEADER: \subjclass[2010]{}

# *** Other formatting settings
#+LATEX_HEADER: \date{}


* Introduction
* Notation and Preliminaries

Let \(\ambient\) be a Riemannian manifold with Levi-Civita connection \(\ambientconx\), and let \(\conformalmap: \ambientspace \to \ambientspace\) a conformal diffeomorphism with
\[
\ambientconformalmetric = \pullback{\conformalmap} \ambientmetric = \conformalfactor \ambientmetric.
\]
We want to compare the geometry of \(\ambient\) with \((\conformalmap(\ambientspace), \ambientmetric)\). To this end we need to identify \(x\) with \(\conformalmap(x)\) which we achieve by comparing \(\ambient\) with \((\ambientspace, \ambientconformalmetric)\) at \(x\) since \(\conformalmap: (\ambientspace, \ambientconformalmetric) \to \ambient\) is an isometry.

The dual conformal metric is
\[
\dualambientconformalmetric = \inverseconformalfactor \dualambientmetric.
\]
The conformal Levi-Civita connection is
\[
\ambientconformalconx_X Y = \ambientconx_X Y + X(\conformalexponent) Y + Y(\conformalexponent) X - \ambientmetric(X, Y) \grad \conformalexponent
\]
where the gradient is taken with respect to the original metric \(\ambientmetric\).

Now let \(\submanifold \subset \ambientspace\) be an submanifold. We want to compare the geometry of \(\submanifold\) with \(\conformalmap(\submanifold)\). To this, we work instead with \(\submanifold\) using the metric \(\ambientconformalmetric\) since the isometry \(\conformalmap: (\ambientspace, \ambientconformalmetric) \to \ambient\) obviously takes \(\submanifold\) isometrically to \(\conformalmap(\submanifold)\). Let \(\metric\) be the metric on \(\submanifold\) induced by \(\ambientmetric\) with Levi-Civita connection \(\conx\) and let \(\conformalmetric\) be the metric induced by \(\ambientconformalmetric\) with Levi-Civita connection \(\conformalconx\). 

Then we have
\[
\conformalmetric = \conformalfactor \metric, \quad \dualconformalmetric = \conformalfactor \dualmetric.
\]

For the connection, let \(X,Y\) be tangent to \(M\) and then taking the tangential component of \(\ambientconformalconx_X Y\) gives,
\[
\conformalconx_X Y = \conx_X Y + X(\conformalexponent) Y + Y(\conformalexponent) X - \metric(X, Y) \grad \conformalexponent
\]
where the gradient is now the gradient on \(M\), taken with respect to \(\metric\).

Letting \(\nor\) be the unit normal vector to \(M\) with respect to \(\ambientmetric\), we see that for any vector \(X\) tangent to \(M\),
\[
\ambientconformalmetric (\nor, X) = \conformalfactor \ambientmetric(\nor, X) = 0
\]
so that \(\nor\) is normal to \(M\) with respect to \(\ambientconformalmetric\). It's length however is now \(\sqrtconformalfactor\) so that
the conformal unit normal is
\[
\conformalnor = \inversesqrtconformalfactor \nor.
\]
This allows us to calculate the second fundamental form,
\begin{align*}
\conformalsff (X, Y) &= \ambientconformalmetric(\conformalconx_X Y, \conformalnor) = \conformalfactor \ambientmetric (\ambientconx_X Y + X(\conformalexponent) Y + Y(\conformalexponent) X - \ambientmetric(X, Y) \grad \conformalexponent, \inversesqrtconformalfactor \nor) \\
&= \sqrtconformalfactor \ambientmetric (\ambientconx_X Y, \nor) - \sqrtconformalfactor \ambientmetric(X, Y) \ambientmetric (\grad \conformalexponent, \nor) \\
&= \sqrtconformalfactor \sff (X, Y) - \sqrtconformalfactor \ambientmetric (X, Y) d\conformalexponent \cdot \nor.
\end{align*}

Taking the trace with respect to \(\dualmetric\) gives the conformal mean curvature,
\[
\conformalmeancurv = \inversesqrtconformalfactor \meancurv - \inversesqrtconformalfactor d\conformalexponent \cdot \nor = \inversesqrtconformalfactor \meancurv - d\conformalexponent \cdot \conformalnor.
\]

* Solitons
* Notes 							   :noexport:
** Comments from Ben
1. Is $n_\delta$ the choice with negative $z$-component?
2. Make more rigorous what is meant by $z$-coord. of $\alpha$ is $\geq z$-coord. of $\beta$. E.g., what points on alpha correspond to what points on beta? One way might be to take the intersection of S^2, P, and span{n,(0,0,1)} as the north and south poles and use the great circles passing through them in S^2_+.
3. Lemma 0.2: $\gamma_+ \geq R(\gamma_-)$ (abbreviated)?
4. Define $\alpha > \beta$ to be strictly greater in the interior of S^2_+ and at the boundary (assume equal there) the angle is positive.
5. Conclusion of Lemma 0.3 is > instead of geq.

